# Generated by Django 4.2.6 on 2023-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_amdcpu_id_alter_amdmotherboard_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amdcpu',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amdmotherboard',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooler',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intelcpu',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intelmotherboard',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psu',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='wattage',
            field=models.IntegerField(default=0),
        ),
    ]
